### ISSUE TITLE
in3 payment method not listed

### ISSUE THREAD

**Issue by Ylmzef** [mollie/magento2-scandipwa#10]
I configured in3 payment method from the admin panel and Mollie dashboard. 
But it's not listed between the payment methods in checkout/billing.

**Comment by Ylmzef** [comment]
It's still not working.
When it's selected by the customer it's forwarding direct tot the checkout/success page, without to payment page of in3.

**Comment by Frank-Magmodules** [comment]
HI @Ylmzef , it's strange as we can't reproduce this, please keep in mind that the In3 payment methods have some [specified requirements](https://help.mollie.com/hc/nl/articles/5614983338514-Hoe-werkt-in3-) as it's only available for dutch customers for example. 

Can you maybe share your environment details through our [secured form](https://www.magmodules.eu/support-form.html) so we can take a look with you on this?
