### ISSUE TITLE
Order still on "Created" status after a successful payment

### ISSUE THREAD

**Issue by Ylmzef** [mollie/magento2-scandipwa#14]
I received a successful payment with iDeal payment methode but the order status still on "Created" status in admin panel and invoice is not generated.
Also worst of all, customer still receives mail from Mollie Payment Reminders.

**Comment by Frank-Magmodules** [comment]
Hello @Ylmzef,

Thanks for opening this issue. I actually think Webhooks aren’t processed.  
Could you check if they are reaching your webserver? 

In the Mollie dashboard, you can see what Mollie did receive as a status code from the request. You can also click the “Fetch Status” button on the order page in the backend. This will run the same code as when a Webhook is being called.

**Comment by Frank-Magmodules** [comment]
HI @Ylmzef , is this issue fixed now in your store?

**Comment by Ylmzef** [comment]
Hi @Frank-Magmodules, yes it's fixed thanks for the support!
