### ISSUE TITLE
webhook error

### ISSUE THREAD

**Issue by Ylmzef** [mollie/magento2-scandipwa#19]
I am getting a webhook error in ScandiPWA, since the last Mollie/Magento2 (v2.27.0) update.

> "Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/overview/handling-errors"

**Comment by Frank-Magmodules** [comment]
Thank you, @Ylmzef. Let's continue to stay in direct contact as we are currently doing to thoroughly investigate this matter.

**Comment by Ylmzef** [comment]
The problem was encountered in versions 2.30.1 and 2.30.0 on mollie/magento2. Donwgraded to version 2.29.1 and its now works fine.

**Comment by Frank-Magmodules** [comment]
Hi @Ylmzef , can you please let me know if you still have this issue on our latest version?

**Comment by Ylmzef** [comment]
Hi @Frank-Magmodules, I have updated to version 2.32.3, and I can confirm that I have not reproduce this issue.

**Comment by Frank-Magmodules** [comment]
Hello @Ylmzef,

Thanks for your answer, and good to hear that your production environment is working properly. For your local environment: The error is quite common, especially for local environments. Before placing an order, Mollie checks that the used domain is actually reachable from the outside. 

With local environments, this is not the case most of the time. This gives you 2 options: Disable the webhooks, or expose your environment to the outside world. More information about this can be found here:
https://github.com/mollie/magento2/wiki/Webhook-Communication-between-your-Magento-webshop-and-Mollie
