### ISSUE TITLE
Not found issue on 'checkout/success' page

### ISSUE THREAD

**Issue by Ylmzef** [mollie/magento2-scandipwa#23]
Upon completing the checkout process, I encountered an issue where the payment success page was loading as a 404 not found page. 
After investigation, I discovered that this error was resolved when I reverted the commit referenced here: [Commit Link](https://github.com/mollie/magento2/commit/b09e5194d803ca6267bd8935d46e1dd217fbf67b). It seems that the error originated from this commit.

![Scherm­afbeelding 2024-03-03 om 04 29 35](https://github.com/mollie/magento2-scandipwa/assets/8562514/2d7a665e-9241-4e1d-ac42-0017c316e201)

**Comment by Frank-Magmodules** [comment]
Thank you, @Ylmzef, for bringing this issue to our attention. 
We're currently investigating it and will get back to you with updates.
